"use client";
/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities, react-hooks/exhaustive-deps */

import { useEffect, useState } from "react";

type Deal = { id:string; title:string; description?:string|null; url:string; imageUrl?:string|null; price:number; marketValue:number|null; profit:number|null; roi:number|null; score:number|null; category?:string|null; confidence:number|null; risk:number|null; country?:string|null; condition?:string|null; publishedAt:string; decision:string };

export function DealLibrary() {
  const [rows,setRows]=useState<Deal[]>([]); const [view,setView]=useState<"grid"|"list">("grid"); const [q,setQ]=useState(""); const [country,setCountry]=useState(""); const [condition,setCondition]=useState(""); const [since,setSince]=useState(""); const [decision,setDecision]=useState(""); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(18); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [busy,setBusy]=useState(true); const [message,setMessage]=useState("");
  async function load(target=page) { setBusy(true); const params=new URLSearchParams({page:String(target),pageSize:String(pageSize)}); if(q)params.set("q",q);if(country)params.set("country",country);if(condition)params.set("condition",condition);if(since)params.set("since",since);if(decision)params.set("decision",decision); const response=await fetch(`/api/deals?${params}`,{cache:"no-store"}); const body=await response.json(); if(response.ok){setRows(body.rows);setPage(body.page);setPages(body.pages);setTotal(body.total);}else setMessage(body.error||"Chargement impossible");setBusy(false);}
  useEffect(()=>{void load(1);},[pageSize]);
  async function decide(id:string,status:string){const response=await fetch("/api/deals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({opportunityId:id,status})});const body=await response.json();if(!response.ok){setMessage(body.error||"Connexion requise");return;}setRows((current)=>current.map((row)=>row.id===id?{...row,decision:status}:row));setMessage("Décision enregistrée dans ton compte.");}
  return <main className="app-page"><header className="page-hero"><p className="eyebrow">Tracker Vinted</p><h1>Deals actifs</h1><p>Les opportunités rentables encore actives, avec leur photo distante, leur score et ton traitement personnel.</p></header>
    <section className="deal-toolbar mt-6"><input className="neu-input" value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Titre, description, pays, état…"/><input className="neu-input" value={country} onChange={(e)=>setCountry(e.target.value)} placeholder="Pays (FR, BE…)"/><input className="neu-input" value={condition} onChange={(e)=>setCondition(e.target.value)} placeholder="État"/><input className="neu-input" type="date" value={since} onChange={(e)=>setSince(e.target.value)}/><select className="neu-input" value={decision} onChange={(e)=>setDecision(e.target.value)}><option value="">Tous mes traitements</option><option value="TO_REVIEW">À traiter</option><option value="VALIDATED">Validés</option><option value="BOUGHT">Achetés</option><option value="IGNORED">Ignorés</option></select><button className="button-primary" onClick={()=>void load(1)}>Filtrer</button></section>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-400"><strong className="text-white">{total}</strong> deal(s)</p><div className="flex gap-2"><select className="neu-input compact" value={pageSize} onChange={(e)=>setPageSize(Number(e.target.value))}><option value="12">12 / page</option><option value="18">18 / page</option><option value="30">30 / page</option><option value="60">60 / page</option></select><button className={`view-toggle ${view==="grid"?"active":""}`} onClick={()=>setView("grid")} aria-label="Vue grille">▦</button><button className={`view-toggle ${view==="list"?"active":""}`} onClick={()=>setView("list")} aria-label="Vue liste">☰</button></div></div>
    {message&&<p className="status-message">{message}</p>}{busy?<div className="loading-panel">Analyse des deals…</div>:<section className={`deal-results ${view}`}>{rows.map((deal)=><article key={deal.id} className="neu-card deal-card">{deal.imageUrl?<img src={deal.imageUrl} alt="" loading="lazy"/>:<div className="image-placeholder">V</div>}<div className="deal-copy"><div className="flex items-start justify-between gap-3"><div><span className="catalog-code">{deal.country||"Pays ?"} · {deal.condition||"État ?"}</span><h2>{deal.title}</h2></div>{deal.score!==null&&<span className="score-pill">{deal.score}/100</span>}</div><p>{deal.description||"Description non fournie"}</p><div className="deal-metrics"><span>Prix<strong>{euro(deal.price)}</strong></span><span>Marché<strong>{deal.marketValue===null?"—":euro(deal.marketValue)}</strong></span><span>Profit<strong className="gain">{deal.profit===null?"—":`+${euro(deal.profit)}`}</strong></span><span>ROI<strong>{deal.roi===null?"—":`${deal.roi.toFixed(0)} %`}</strong></span></div><small>Publiée {new Date(deal.publishedAt).toLocaleString("fr-FR")}</small><div className="deal-actions"><a href={deal.url} target="_blank" rel="noreferrer" className="neu-button">Voir l'annonce ↗</a><button className={deal.decision==="VALIDATED"?"button-primary":"neu-button"} onClick={()=>void decide(deal.id,"VALIDATED")}>Valider</button><button className={deal.decision==="BOUGHT"?"button-primary":"neu-button"} onClick={()=>void decide(deal.id,"BOUGHT")}>Acheté</button><button className={deal.decision==="IGNORED"?"danger-button":"neu-button"} onClick={()=>void decide(deal.id,"IGNORED")}>Ignorer</button></div></div></article>)}{!rows.length&&<div className="neu-card p-8 text-slate-400">Aucun deal ne correspond à ces filtres.</div>}</section>}
    <div className="pagination"><button className="neu-button" disabled={page<=1} onClick={()=>void load(page-1)}>← Précédent</button><span>Page {page} / {pages}</span><button className="neu-button" disabled={page>=pages} onClick={()=>void load(page+1)}>Suivant →</button></div>
  </main>;
}
const euro=(value:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(value);
